# Required configuration
source: source
destination: public
code_dir: downloads/code
port: 4000

url: http://dev.octopress.org
title: Octopress
subtitle: A blogging framework for hackers.
author: Your Name
subscribe_rss: /atom.xml
subscribe_email:

markdown: kramdown
pygments: true
recent_posts: 1
simple_search: http://google.com/search

# Optional configurations

# For RSS Feed
email:

# Twitter
twitter_user: imathis
twitter_tweet_count: 4
twitter_show_replies: false
twitter_follow_button: true
twitter_show_follower_count: false
twitter_tweet_button: true

# Pinboard
#pinboard_user: imathis
pinboard_count: 3

# Delicious
delicious_user:
delicious_count: 3

# Disqus Comments
disqus_short_name:

# Google Analytics
google_analytics_tracking_id:
