source: source
destination: site
markdown: rdiscount
pygments: true
permalink: /blog/:year/:month/:day/:title
url: http://yoursite.com
multiviews: true
sass: false
haml: true
post_defaults:
  layout: blog_post