#   Copyright (c) 2010, Diaspora Inc.  This file is
#   licensed under the Affero General Public License version 3.  See
#   the COPYRIGHT file.



development:
  debug: false
  socket_debug : false
  socket_host: 0.0.0.0
  socket_port: 8080
  socket_collection_name: 'websocket'
  pubsub_server: 'https://pubsubhubbub.appspot.com/'

test:
  debug: false
  socket_debug : false
  socket_host: 0.0.0.0
  socket_port: 8081
  pubsub_server: 'https://pubsubhubbub.appspot.com/'

production:
  debug: false
  socket_debug : false
  socket_host: 0.0.0.0
  socket_port: 8080
  pubsub_server: 'https://pubsubhubbub.appspot.com/'
