#   Copyright (c) 2010, Diaspora Inc.  This file is
#
#   licensed under the Affero General Public License version 3.  See
#   the COPYRIGHT file.



development:
  debug: false
  socket_debug : false
  socket_port: 8080
  pubsub_server: 'https://pubsubhubbub.appspot.com/'
  attachment_storage: 'file'

test:
  debug: false
  socket_debug : false
  socket_port: 8081
  pubsub_server: 'https://pubsubhubbub.appspot.com/'
  attachment_storage: 'file'

production:
  debug: false
  socket_debug : false
  socket_port: 8080
  pubsub_server: 'https://pubsubhubbub.appspot.com/'

