default: 'en'
available:
  ca: "CatalÃ "
  cs: 'ÄŒeÅ¡tina'
  cy: 'Cymraeg'
  da: 'Dansk'
  de: 'Deutsch'
  el: "Î•Î»Î»Î·Î½Î¹ÎºÎ¬"
  en: 'English'
  en_shaw: 'ğ‘¦ğ‘™ğ‘¤ğ‘¦ğ‘–'
  es: 'EspaÃ±ol'
  es-CL: 'EspaÃ±ol Chileno'
  fi: 'Suomi'
  fr: 'FranÃ§ais'
  ga: 'Gaeilge'
  he: '×¢×‘×¨×™×ª'
  hu: 'magyar nyelv'
  id: 'Bahasa Indonesia'
  it: 'Italiano'
  lt: 'LietuviÅ¡kai'
  mk: 'Ğ¼Ğ°ĞºĞµĞ´Ğ¾Ğ½ÑĞºĞ¸'
  nb: 'Norske'
  nl: 'Nederlands'
  pl: "Polski"
  pt-BR: 'PortuguÃªs'
  ro: 'RomÃ¢nÄƒ'
  ru: 'Ğ ÑƒÑÑĞºĞ¸Ğ¹'
  sl: 'SlovenÅ¡Äina'
  sk: 'SlovenÄina'
  sv: 'Svenska'
  tr: 'TÃ¼rk'
