default: "en"
available:
  bg: "Ğ±ÑŠĞ»Ğ³Ğ°Ñ€ÑĞºĞ¸ ĞµĞ·Ğ¸Ğº"
  br: "Brezhoneg"
  ca: "CatalÃ "
  cs: "ÄŒeÅ¡tina"
  cy: "Cymraeg"
  da: "Dansk"
  de: "Deutsch"
  el: "Î•Î»Î»Î·Î½Î¹ÎºÎ¬"
  en: "English"
  en_shaw: "ğ‘¦ğ‘™ğ‘¤ğ‘¦ğ‘–"
  es: "EspaÃ±ol"
  es-CL: "EspaÃ±ol Chileno"
  eu: "Euskara"
  fi: "Suomi"
  fr: "FranÃ§ais"
  ga: "Gaeilge"
  gl: "Galego"
  he: "×¢×‘×¨×™×ª"
  hu: "magyar nyelv"
  id: "Bahasa Indonesia"
  is: "Ã­slenska"  
  it: "Italiano"
  ko: "í•œêµ­ì–´"
  lt: "LietuviÅ¡kai"
  mk: "Ğ¼Ğ°ĞºĞµĞ´Ğ¾Ğ½ÑĞºĞ¸"
  ml: "à´®à´²à´¯à´¾à´³à´‚"
  nb: "Norske"
  nl: "Nederlands"
  pa: "à¨ªà©°à¨œà¨¾à¨¬à©€"
  pl: "polski"
  pt-BR: "PortuguÃªs"
  ro: "RomÃ¢nÄƒ"
  ru: "Ğ ÑƒÑÑĞºĞ¸Ğ¹"
  sl: "SlovenÅ¡Äina"
  sk: "SlovenÄina"
  sv: "Svenska"
  tr: "TÃ¼rk"
  zh-CN: "ä¸­æ–‡"
  zh-TW: "å°ç£ä¸­æ–‡"
fallbacks:
  en-GB:
    - :en
  en-US:
    - :en
  en_shaw:
    - :en
    - :en-GB
    - :en-US
  sv:
    - :sv-SE
  he:
    - :he-IL
  es-CL:
    - :es
  gl:
    - :gl-ES
  zh:
    - :zh-CN
    - :zh-TW
rtl:
  - :ar
  - :he
