default: "en"


available:
  ar: "Ø§Ù„Ø¹Ø±Ø¨ÙŠØ©"
  art-nvi: "Na'vi"
  bg: "Ğ±ÑŠĞ»Ğ³Ğ°Ñ€ÑĞºĞ¸ ĞµĞ·Ğ¸Ğº"
  br: "Brezhoneg"
  ca: "CatalÃ "
  cs: "ÄŒeÅ¡tina"
  cy: "Cymraeg"
  da: "Dansk"
  de: "Deutsch"
  de_formal: "Deutsch (Sie)"
  el: "Î•Î»Î»Î·Î½Î¹ÎºÎ¬"
  en: "English"
  en_1337: "3n6l15h (English 1337)"
  en_pirate: "English (Pirate)"
  en_shaw: "ğ‘¦ğ‘™ğ‘¤ğ‘¦ğ‘–"
  eo: "Esperanto"
  es: "Castellano"
  es-AR: "Castellano - Argentina"
  es-CL: "Castellano - Chile"
  es-MX: "EspaÃ±ol, MÃ©xico"
  et: "Eesti"
  eu: "Euskara"
  fi: "Suomi"
  fil: "Filipino"
  fr: "FranÃ§ais"
  ga: "Gaeilge"
  gl: "Galego"
  he: "×¢×‘×¨×™×ª"
  hu: "magyar nyelv"
  id: "Bahasa Indonesia"
  is: "Ã­slenska"
  it: "Italiano"
  ja: "æ—¥æœ¬èª"
  ka: "áƒ¥áƒáƒ áƒ—áƒ£áƒšáƒ˜"
  ko: "í•œêµ­ì–´"
  lt: "LietuviÅ¡kai"
  mk: "Ğ¼Ğ°ĞºĞµĞ´Ğ¾Ğ½ÑĞºĞ¸"
  ml: "à´®à´²à´¯à´¾à´³à´‚"
  ms: "Ø¨Ù‡Ø§Ø³ Ù…Ù„Ø§ÙŠÙˆâ€"
  nb: "Norske"
  nl: "Nederlands"
  nn: "Nynorsk"
  pa: "à¨ªà©°à¨œà¨¾à¨¬à©€"
  pl: "polski"
  pt-BR: "PortuguÃªs"
  ro: "RomÃ¢nÄƒ"
  ru: "Ğ ÑƒÑÑĞºĞ¸Ğ¹"
  sk: "SlovenÄina"
  sl: "SlovenÅ¡Äina"
  sq: "gjuha shqipe"
  sv: "Svenska"
  te: "à°¤à±†à°²à±à°—à±"
  tr: "TÃ¼rk"
  uk: "ÑƒĞºÑ€Ğ°Ñ—ÌĞ½ÑÑŒĞºĞ° Ğ¼Ğ¾ÌĞ²Ğ°"
  ur-PK: "Ø§ÙØ±Ø¯Ùˆ (Ù¾Ø§Ú©Ø³ØªØ§Ù†)"
  vi: "TiÃªÌng ViÃªÌ£t"
  zh-CN: "ä¸­æ–‡"
  zh-TW: "å°ç£ä¸­æ–‡"


fallbacks:
  en-GB:
    - "en"
  en-US:
    - "en"
  en_shaw:
    - "en"
    - "en-GB"
    - "en-US"
  en_pirate:
    - "en"
    - "en-GB"
    - "en-US"
  en_1337:
    - "en"
    - "en-GB"
    - "en-US"
  sv:
    - "sv-SE"
  he:
    - "he-IL"
  es-AR:
    - "es"
  es-CL:
    - "es"
  es-MX:
    - "es"
  gl:
    - "gl-ES"
  zh:
    - "zh-CN"
    - "zh-TW"
  ur-PK:
    - "ur"
  de_formal:
    - "de"
  art_nvi:
    - "art-nvi"


rtl:
  - "ar"
  - "he"
  - "ur"
  - "ur-PK"
  - "ms"
